config/routes.rb
OurnaropaCalendar::Engine.routes.draw do
  resources :events, path: '/event', except: [:index, :edit, :destroy]
  
  get 'view/:date', to: 'events#index', as: :view
  
  #get 'new-event', to: 'events#new'
  
  #get 'event/:id', to: 'events#show', as: :event
  
  get 'event/:id/edit/:edit_code', to: 'events#edit', as: :edit_event
  
  match 'event/:id/delete/:edit_code', to: 'events#destroy', via: :delete, as: :delete_event
  
  #match 'event', to: 'events#create', :via => [:post]
  
  #patch 'event/:id'
  
  root 'events#index'
  
end

app/models/ournaropa_calendar/event.rb
module OurnaropaCalendar

  
  # validates that event starts before it ends
  class MyValidator < ActiveModel::Validator
    def validate(record)      
            
      if record.errors[:start_time].length == 0 and record.start_time.nil?
        record.errors[:start_time] << 'was not understood. Sorry!'
      end

      if record.errors[:end_time].length == 0 and record.end_time.nil?
        record.errors[:end_time] << 'was not understood. Sorry!'
      end
      
      if record.errors[:start_time].length == 0 and record.errors[:end_time].length == 0      
        if record.start_time > record.end_time
          record.errors[:end_time] << 'cannot be prior to starting time'
        end    
      end
      
    end
  end
   
  
  class Event < ActiveRecord::Base
        
    attr_accessor :start_time_text, :end_time_text
    
    # if loaded from database, define start_time_text and end_time_text
    after_find do |event|
      if self.start_time.present?
        event.start_time_text = self.start_time.strftime("%-m/%-d/%Y %l:%M %p")
      end
      
      if event.end_time.present?
        event.end_time_text = self.end_time.strftime("%-m/%-d/%Y %l:%M %p")
      end
    end
    
    scope :relevant, ->(time_boundaries) { where("(start_time >= :start_time AND start_time < :end_time) OR (end_time > :start_time AND end_time <= :end_time) OR (start_time <= :start_time AND end_time >= :end_time)", {:start_time => time_boundaries[:start], :end_time => time_boundaries[:end] }).order("start_time") }
    
    validates :title, length: { minimum: 2 }
    
    include ActiveModel::Validations
    validates_with MyValidator
    
    validates :location, presence: true
    
    before_validation :parse_start_and_end_times
    
    # before creation: create edit code
    before_create do
      self.edit_code = SecureRandom.hex(5).upcase
    end
    
    # gets the event duration in days
    def duration_in_days
      
      num_days = ((self.end_time.beginning_of_day - self.start_time.beginning_of_day) / 1.day).round
      
      # if event ends at midnight, don't count this as a new day
      if self.ends_at_midnight? and start_time != end_time
        num_days -= 1
      end
        
      return num_days  
      
    end
      
    # does the event end at midnight?
    def ends_at_midnight?
      if self.end_time == self.end_time.beginning_of_day
        return true
      else
        return false
      end
    end
    
      
    private
    
      def parse_start_and_end_times
        
        if self.start_time_text.present?
          self.start_time = Chronic.parse(self.start_time_text)
        else
          self.errors[:start_time] << 'can\'t be blank'
        end  
  
        if self.end_time_text.present?
          self.end_time = Chronic.parse(self.end_time_text)
        else
          self.errors[:end_time] << 'can\'t be blank'
        end
        
      end
    
    
      def is_relevant? time_start, time_end
        if (self.start_time >= time_start and self.start_time < time_end) || (self.end_time > time_start and self.end_time <= time_end) || (self.start_time <= time_start and self.end_time >= time_end)
          return true
        else
          return false
        end
      end
    
  end
end

app/controllers/ournaropa_calendar/application_controller.rb
module OurnaropaCalendar
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/ournaropa_calendar/events_controller.rb
require_dependency "ournaropa_calendar/application_controller"

module OurnaropaCalendar
  class EventsController < ::ApplicationController
    
    before_action :set_event, only: [:show, :edit, :update, :destroy]

    # inherit the layout from the main application
    layout 'application'
    
    require "time"
    require 'chronic'
    
    # for important functions
    include EventsHelper
    
    # if wrong id
    rescue_from ActiveRecord::RecordNotFound do |exception|
      render 'not_found'
    end

    # GET /events
    def index
      
      @show_date = params[:date].present? ? Date.strptime(params[:date], "%b+%Y").to_time : Time.zone.now
      
      @events = Event.relevant({start: get_calendar_start_date(@show_date), end: get_calendar_end_date(@show_date)})
      
      # parse to days
      @events_by_day = Hash.new
      
      @events.each do |event|
        for i in 0..event.duration_in_days do
          
          # if no events have been saved for this day yet, then create it
          if @events_by_day[(event.start_time + i.day).strftime("%Y-%m-%d").to_s].nil?
            @events_by_day[(event.start_time + i.day).strftime("%Y-%m-%d").to_s] = []
          end
            
          @events_by_day[(event.start_time + i.day).strftime("%Y-%m-%d").to_s].push(event)
        end
      end
    end

    # GET /events/1
    def show
      if @event.nil?
        puts "lol"
      end
    end

    # GET /events/new
    def new
      @event = Event.new
    end

    # GET /events/1/edit
    def edit
      redirect_to @event, notice: "Cannot edit event: The link you provided does not match the event's key code." unless @event.edit_code == params[:edit_code]
    end

    # POST /events
    def create      
      @event = Event.new(event_params)


      if @event.save
        redirect_to @event, flash: { show_edit_code: true }
      else
        render :new
      end
    end

    # PATCH/PUT /events/1
    def update
      if @event.update(event_params)
        redirect_to @event, notice: 'Event was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /events/1
    def destroy
      
      redirect_to @event, notice: "Cannot delete event: The link you provided does not match the event's key code." unless @event.edit_code == params[:edit_code]
      
      @event.destroy
      redirect_to root_url, notice: 'Event was successfully deleted.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_event
        @event = Event.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def event_params
        params.require(:event).permit(:title, :description, :start_time_text, :start_time, :end_time_text, :end_time, :location, :organizer_name, :organizer_email)
      end
  end
end

app/helpers/ournaropa_calendar/application_helper.rb
module OurnaropaCalendar
  module ApplicationHelper
  end
end

app/helpers/ournaropa_calendar/events_helper.rb
module OurnaropaCalendar
  module EventsHelper
    
    require "time"
    
    def days_of_the_week
      return ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    end
    
    def seconds_per_day
      return 24*60*60;
    end
    
    def get_calendar_start_date time
      return time.beginning_of_month.beginning_of_week
    end
    
    def get_calendar_end_date time
      return time.end_of_month.end_of_week
    end
    
    def get_days_in_calendar time
      #puts ((get_calendar_end_date(time) - get_calendar_start_date(time)) / seconds_per_day).round
      return ((get_calendar_end_date(time) - get_calendar_start_date(time)) / seconds_per_day).round
    end
  
    # checks if two dates are in the same year
    def is_same_year? date1, date2
      return date1.beginning_of_year == date2.beginning_of_year
    end
    
    # checks if two dates are in the same month
    def is_same_month? date1, date2
      return date1.beginning_of_month == date2.beginning_of_month
    end
    
    # checks if two dates are on the same day
    def is_same_day? date1, date2
      return date1.beginning_of_day == date2.beginning_of_day || (date2 == date2.beginning_of_day and date1.beginning_of_day == date2.yesterday.beginning_of_day)
    end

    # formatting of start and end time
    def format_start_and_end_date start_time, end_time
      
      # if end time is midnight, it's not a new day
      if end_time == end_time.beginning_of_day and start_time != end_time
        end_time -= 1
      end
      
      if is_same_day?(start_time, end_time)
        return start_time.strftime("%a, %b %e, %Y")
      elsif is_same_year?(start_time, end_time)
        return start_time.strftime("%a, %b %e") + " - " + end_time.strftime("%a, %b %e, %Y")
      else
        return start_time.strftime("%a, %b %e, %Y") + " - " + end_time.strftime("%a, %b %e, %Y")
      end
    end        
    
    # formatting of start and end time
    def format_start_and_end_time start_time, end_time
      
      # if all day
      if start_time == start_time.beginning_of_day and end_time == end_time.beginning_of_day and start_time != end_time
        return "all day"
        
      # if start time equals end time, just give start time
      elsif start_time == end_time 
        return start_time.strftime("%l:%M %P")
      elsif end_time == end_time.beginning_of_day
        return start_time.strftime("%l:%M %P") + " - midnight"
      else
        return start_time.strftime("%l:%M %P") + " - " + end_time.strftime("%l:%M %P")
      end
      
    end    
      
    # formats an event time to show on calendar main view
    def format_time current_day, start_time, end_time
      
      # multi-day event?
      if start_time < current_day.beginning_of_day or (start_time == start_time.beginning_of_day and end_time > current_day) or (start_time == start_time.beginning_of_day and end_time == end_time.beginning_of_day and start_time != end_time)
        return ""
      end
      
      # start with hour
      formatted_string = start_time.strftime("%l")
      
      # add minutes if non-zero
      formatted_string += start_time.strftime("%M") == "00" ? "" : ":" + start_time.strftime("%M")
      
      # add PM if not am
      formatted_string += start_time.strftime("%P") == "am" ? "" : "p"
      
      return formatted_string
    end
    
  end
end

app/views/ournaropa_calendar/events/_form.html.erb
  <%= form_for(@event) do |f| %>
  
   <% if @event.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h4>

      <ul class="collection">
      <% @event.errors.full_messages.each do |message| %>
        <li class="collection-item"><%= message %></li>
      <% end %>
      </ul>
    </div>
    <div class="divider"></div>
  <% end %>
  
  <div class="row">
    <div class="input-field col s12">
      
      <i class="material-icons prefix">star</i>
      <%= f.text_field :title, :class => "validate" %>
      <%= f.label :title, "What is the event called?" %><br>
    </div>
  </div>
  
  <div class="row">
    <div class="input-field col s12 l6">
      <i class="material-icons prefix">event</i>
      <%= f.text_field :start_time_text, :class => "validate tooltipped", :data => {:position => "bottom", :delay => "50", :tooltip => "Type 'Tomorrow at 6pm' or '4/21/2016 at 11am'"} %>
      <%= f.label :start_time_text, "When does the event start?" %><br>
    </div>
    <div class="row hide-on-large-only"></div>
    <div class="input-field col s12 l6">
      <i class="material-icons prefix">rotate_90_degrees_ccw</i>
      <%= f.text_field :end_time_text, :class => "validate tooltipped", :data => {:position => "bottom", :delay => "50", :tooltip => "Type 'Tomorrow at 6pm' or '4/21/2016 at 11am'"} %>
      <%= f.label :end_time_text, "When does the event end?" %><br>
    </div>
  </div>
  
  <div class="row">
    <div class="input-field col s12">
      
      <i class="material-icons prefix">place</i>
      <%= f.text_field :location, :class => "validate" %>
      <%= f.label :location, "Where will the event happen?" %><br>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12 m12 l6">
      <i class="material-icons prefix">account_circle</i>
      <%= f.text_field :organizer_name, :class => "validate tooltipped", :data => {:position => "bottom", :delay => "50", :tooltip => "Adding your name gives folks an idea of who is organizing this event"}  %>
      <%= f.label :organizer_name, "What is your name / the name of the event organizer? (Optional)" %><br>
    </div>
    <div class="row hide-on-large-only"></div>
    <div class="input-field col s12 m12 l6">
      <i class="material-icons prefix">email</i>
      <%= f.text_field :organizer_email, :class => "validate tooltipped", :data => {:position => "bottom", :delay => "50", :tooltip => "Adding your email address allows people to get in touch with you with questions"}  %>
      <%= f.label :organizer_email, "What is your / the organizer's email address? (Optional)" %><br>
    </div>
  </div>  
  
  <div class="row">
    <div class="input-field col s12">
      
      <i class="material-icons prefix">description</i>
      <%= f.text_area :description, :class => "materialize-textarea" %>
      <%= f.label :description, "Anything else? (Optional)" %>
    </div>
  </div>
  
  <div class="row">
    <div class="col s12 center-align">
      <button class="btn-large red waves-effect waves-light" type="submit" name="action"><%= submit_action %>
        <i class="material-icons right">check</i>
      </button>    
    </div>
  </div>
  
  
  <% end %>

app/views/ournaropa_calendar/events/edit.html.erb
<div id="events" class="edit container">

  <div class="row">
    
    <div class="col s6 m6">
      <%= link_to root_path, :class => "waves-effect waves-light btn" do %>
        <i class="material-icons left">keyboard_arrow_left</i> Back to Calendar
      <% end %>
    </div>
    
    <div class="col s6 m6 right-align">
      <%= link_to 'Delete Event', delete_event_path(@event, @event.edit_code), method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn grey" %>
    </div>


  </div>  
  
  <div class="row">
    <h2 class="left-align">Editing Event</h2>  
    <div class="divider"></div>
  </div>
    
  <%= render partial: "form", locals: {submit_action: "Update Event"} %>
  
</div>

app/views/ournaropa_calendar/events/index.html.erb
<div id="events" class="index container">
  <div class="row">

    <h1 class="center-align">OurNaropa Calendar</h1>  
    <p class="center-align">Discover what's happening at Naropa, add your events, and share with friends.</p>
    
  </div>  
  
  <div class="row">
    
    <div class="col s12 m5 push-m7 right-align">
      <%= link_to new_event_path, :class => "waves-effect waves-light btn red" do %>
        <i class="material-icons left">add</i> Add Event
      <% end %>       
    </div>
    
    <div class="row hide-on-med-and-up"></div>
    
    <div class="col s12 m7 pull-m5 left-align">
        <%= link_to view_path(@show_date.prev_month.strftime("%b+%Y")), :class => "waves-effect waves-light btn tooltipped",  :data => {:position => "right", :delay => "50", :tooltip => "Previous month"} do %>
          <i class="material-icons">keyboard_arrow_left</i>
        <% end %>

        <h5 id="focus"><%= @show_date.strftime("%b %Y") %></h5>

        <%= link_to view_path(@show_date.next_month.strftime("%b+%Y")), :class => "waves-effect waves-light btn tooltipped",  :data => {:position => "right", :delay => "50", :tooltip => "Next month"} do %>
          <i class="material-icons">keyboard_arrow_right</i>
        <% end %>
      
        <%= link_to root_path, :title => "Today", :class => "waves-effect waves-light btn tooltipped hide-on-med-and-down", :data => {:position => "right", :delay => "50", :tooltip => "Show today"} do %>
          <i class="material-icons">today</i>
        <% end %>
      
    </div>

  </div>
    
  <div class="row">
    <table id="calendar" class="bordered">
      <thead>
        <tr>
          <% days_of_the_week.each do |day| %>
            <th class="center-align"><%= day %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        
        <% #print the calendar %>
        
        <% current_date = get_calendar_start_date(@show_date) %>
        
        <% for day in 0..(get_days_in_calendar(@show_date) -1) do %>
                
          <% if current_date == current_date.beginning_of_week %>
            <tr>
          <% end %>
              
              <% #check if current date is in the same month as the calendar -- if not, let's fade the date a bit %>
              <td id="<%= current_date.strftime("%Y-%m-%d") %>" class="day <%= is_same_month?(@show_date, current_date) ? '' : 'faded' %> <%= Time.zone.now.beginning_of_day == current_date.beginning_of_day ? "today" : "" %>">
                <div class="date-indicator left-align"><span><%= (get_calendar_start_date(@show_date) + day * seconds_per_day).strftime("%e") # print the day number
                  %></span></div>
                
                
                <% # run through all events of the day and render them 
                  if @events_by_day[current_date.strftime("%Y-%m-%d")]
                    current_date_events = @events_by_day[current_date.strftime("%Y-%m-%d")]
                    current_date_events.each_with_index do |event, index| %>
                
                    <div class="event"><%= link_to event do %><%= (format_time(current_date, event.start_time, event.end_time) + " " + event.title).strip %><% end %></div>
                
                    <!--
                    <% #no more events if we hit 3
                      if index < 3 || current_date_events.count == index+1 %>
                        <div class="event"><%= (format_time(current_date, event.start_time, event.end_time) + " " + event.title).strip %></div>
                    <% else %>
                        <div class="event more">and <%= pluralize(current_date_events.count - 3, "more event") %> </div>
                        <%# break
    %>
                    <%  end %>-->
                
              <% end
                end %>

              </td>
              
              
          <% if current_date == current_date.end_of_week %>
            </tr>
          <% end %>
        
        
          <% #advance day forward
            current_date = current_date.tomorrow %>
        
        <% end %>
        <tr></tr>
      
      </tbody>
    </table>

  </div>
</div>


<script type="text/javascript">
    
  // check if a day has more than three events - if so, then collapse
  /* DISABLED COLLAPSIBLE 2016-04-02
  var MAX_EVENTS = 4;
  $("td.day").each(function (){
    
    if( $(this).children("div.event").length > MAX_EVENTS){
      
      // do the hiding
      $(this).children("div.event:nth-of-type(n+"+(MAX_EVENTS+1)+")").hide(0);
      
      $(this).append('<div class="event show-all">and ' + ($(this).children("div.event").length - (MAX_EVENTS-1)) + ' more events</div>')
    }
  });
  
  // if click show-all, then show all events
  $(".show-all").click(function() {
    $(this).slideUp();
    
    $(this).siblings("div.event").slideDown();
  });*/
  

</script>

app/views/ournaropa_calendar/events/new.html.erb
<div id="events" class="new container">

  <div class="row">
    
    <%= link_to root_path, :class => "waves-effect waves-light btn" do %>
      <i class="material-icons left">keyboard_arrow_left</i> Back to Calendar
    <% end %>

  </div>  
  
  <div class="row">
    <h2 class="left-align">Add Event</h2>  
    <div class="divider"></div>
  </div>
    
  <%= render partial: "form", locals: {submit_action: "Add Event"} %>
  
</div>

app/views/ournaropa_calendar/events/not_found.html.erb
<div id="events" class="not_found container">
  <div class="row">
    
    <%= link_to root_path, :class => "waves-effect waves-light btn" do %>
      <i class="material-icons left">keyboard_arrow_left</i> Back to Calendar
    <% end %>

  </div>
  
  <div class="row">
    
    <h2 class="left-align">Sorry!</h2>  
    <div class="divider"></div>
  </div>
  
  <div class="row">
    <div class="col s12 center-align">
      <i class="material-icons large">sentiment_neutral</i>
      <h5>Under the given address, no event could be found. Maybe it was deleted. Maybe it never existed.</h5>
    </div>
  </div>
  
  <div class="row">
    <div class="col s12 center-align">
      <%= link_to "Go to Calendar", root_path, class: "waves-effect waves-light btn-large" %>
    </div>
  </div>
    
  <div class="row">
  </div>
</div

app/views/ournaropa_calendar/events/show.html.erb
<div id="events" class="show container">
  <div class="row">
    
    <%= link_to view_path(@event.start_time.strftime("%b+%Y")), :class => "waves-effect waves-light btn" do %>
      <i class="material-icons left">keyboard_arrow_left</i> Back to Calendar
    <% end %>

  </div>
    
  <% # show edit code if event was just created
  if flash[:show_edit_code] %>
    <div class="row">
      <div class="col s12 ">
        <div class="card card-dark red">
          <div class="card-content white-text">
            <span class="card-title"><i class="material-icons md-36 prefix">check_circle</i> Event Saved</span>
            <div class="row">
              <div class="col s12">
                <p>The following link allows you to edit this event later. Please save it carefully.</p>
              </div>
            </div>
            <div class="row no-spacing">
              <div class="input-field col s12">
                <i class="material-icons prefix white-text">link</i>
                <input id="copy-edit-url-text" class="white-text white-border" type="text" value="<%= edit_event_url(@event, @event.edit_code) %>" readonly="readonly">
                <label class="white-text" for="url">URL / Link</label>

              </div>
            </div>
          </div>
          <div class="card-action red darken-2">
            <a id="copy-edit-url" class="white-text">Copy URL to Clipboard</a>
          </div>
        </div>
      </div>
    </div>   
  
  <% end %>
  
  <div class="row">
    
    <h2 class="left-align"><%= @event.title %></h2>  
    <div class="divider"></div>
  </div>
    
  <div class="row">
    <h5><i class="material-icons md-36 prefix">event</i> <%= format_start_and_end_date(@event.start_time, @event.end_time) %></h5>
    <h5><i class="material-icons md-36 prefix">schedule</i> <%= format_start_and_end_time(@event.start_time, @event.end_time) %></h5>
    <h5><i class="material-icons md-36 prefix">place</i> <%= @event.location %></h5>
    <% #show organizer if present
      if @event.organizer_name.present? %>
    <h5><i class="material-icons md-36 prefix">account_circle</i> Organizer: <%= @event.organizer_name %>
      <% if @event.organizer_email.present? %>
        &middot; <%= mail_to(@event.organizer_email, nil, :encode => :javascript) %>
      <% end %>
    </h5>
    <% end %>
    <div class="divider"></div>
  </div>  
  
  <div class="row">
    <div class="description">
      <p><i class="material-icons md-36 prefix">description</i><%= @event.description.present? ? h(@event.description).gsub("\n","<br />").html_safe : "No description." %></p>
    </div>
    <div class="divider"></div>
  </div>
  
  <!-- sharing -->
  <div class="row">
    <div class="col s12 m6 l4 sharing">
      <div class="col s3">
        <%= link_to "https://www.facebook.com/sharer/sharer.php?u=" + URI.encode(request.original_url), :target => "_blank" do %>
          <%= image_tag "ournaropa_calendar/fb-icon.png", :class => "tooltipped responsive-img", :data => {:position => "top", :delay => "50", :tooltip => "Share on Facebook"} %>
        <% end %>
      </div>
      <div class="col s3">
        <%= link_to "https://twitter.com/intent/tweet?text=" + URI.escape("Check out " + @event.title + ": " + request.original_url), :target => "_blank" do %>
          <%= image_tag "ournaropa_calendar/twitter-icon.png", :class => "tooltipped responsive-img", :data => {:position => "top", :delay => "50", :tooltip => "Share on Twitter"} %>
        <% end %>
      </div>
      <div class="col s3">
        <a id="copy-url">
          <%= image_tag "ournaropa_calendar/url-icon.png", :class => "tooltipped responsive-img", :data => {:position => "top", :delay => "50", :tooltip => "Copy Event URL to Clipboard"} %>
        </a>
      </div>
    
      <!-- Save to Google Calendar -->
      <div class="col s3">
        
        <% google_description = ""
          if @event.organizer_name.present? || @event.organizer_email.present?
            google_description += "Organizer:"
          end
          if @event.organizer_name.present?
            google_description += " " + @event.organizer_name
          end
          if @event.organizer_email.present?
            google_description += " (" + @event.organizer_email+ ")"
          end

          if (@event.organizer_email.present? || @event.organizer_name.present?) && @event.description.present?
            google_description += "\n\n"
          end
          if @event.description.present?
            google_description += @event.description
          end %>
        
          <%= link_to "https://calendar.google.com/calendar/render?dates=" + @event.start_time.strftime("%Y%m%dT%H%M%S") + "/" + @event.end_time.strftime("%Y%m%dT%H%M%S") + "&ctz=America/Denver&action=TEMPLATE&text=" + URI.encode(@event.title) + "&location=" + URI.encode(@event.location) + "&details=" + URI.encode(google_description), :target => "_blank" do %>
        <%= image_tag "ournaropa_calendar/gcal-icon.png", :class => "tooltipped responsive-img", :data => {:position => "top", :delay => "50", :tooltip => "Save Event in Google Calendar"} %>
          <% end %>
      </div>
      
      <div id="copy-url-textfield" class="row" style="display:none;">
        <div class="col s12">
          <div class="row">
            <div class="input-field col s6">
              <i class="material-icons prefix">link</i>
              <input id="url" type="text" value="<%= event_url(@event) %>" readonly="readonly">
              <label for="url">URL / Link</label>

            </div>
          </div>
        </div>
      </div>
      
    </div>
  </div>
  
  <div class="row">
    
    <%= link_to view_path(@event.start_time.strftime("%b+%Y")), :class => "waves-effect waves-light btn" do %>
      <i class="material-icons left">keyboard_arrow_left</i> Back to Calendar
    <% end %>

  </div>
  
</div>


<script type="text/javascript">
    
  $("#copy-url").click(function(){
  
    // show url copy thing
    $("#copy-url-textfield").slideDown();
    
    // do the copying
    var copyTextarea = document.querySelector('#copy-url-textfield input');
    copyTextarea.select();
  
    try {
      var successful = document.execCommand('copy');
      var msg = successful ? 'successful' : 'unsuccessful';
      if(msg == "successful")
        Materialize.toast('URL copied to clipboard!', 4000); // 4000 is the duration of the toast
    } catch (err) {
      Materialize.toast('Error copying URL... Please copy manually', 4000); // 4000 is the duration of the toast
    }
    
    
  });
  
  // copy edit url
  $("#copy-edit-url").click(function(){
  
    
    // do the copying
    var copyTextarea = document.querySelector('#copy-edit-url-text');
    copyTextarea.select();
  
    try {
      var successful = document.execCommand('copy');
      var msg = successful ? 'successful' : 'unsuccessful';
      if(msg == "successful")
        Materialize.toast('URL copied to clipboard!', 4000); // 4000 is the duration of the toast
    } catch (err) {
      console.log('Oops, unable to copy');
      Materialize.toast('Error copying URL... Please copy manually', 4000); // 4000 is the duration of the toast
    }
    
    
  });

</script>